var districts = [
    "BARGUNA",
    "BARISAL",
    "BHOLA",
    "JHALOKATI",
    "PATUAKHALI",
    "PIROJPUR",
    "BANDARBAN",
    "BRAHMANBARIA",
    "CHANDPUR",
    "CHITTAGONG",
    "COMILLA",
    "COX'S BAZAR",
    "FENI",
    "KHAGRACHHARI",
    "LAKSHMIPUR",
    "NOAKHALI",
    "RANGAMATI",
    "DHAKA",
    "FARIDPUR",
    "GAZIPUR",
    "GOPALGANJ",
    "JAMALPUR",
    "KISHOREGONJ",
    "MADARIPUR",
    "MANIKGANJ",
    "MUNSHIGANJ",
    "MYMENSINGH",
    "NARAYANGANJ",
    "NARSINGDI",
    "NETRAKONA",
    "RAJBARI",
    "SHARIATPUR",
    "SHERPUR",
    "TANGAIL",
    "BAGERHAT",
    "CHUADANGA",
    "JESSORE",
    "JHENAIDAH",
    "KHULNA",
    "KUSHTIA",
    "MAGURA",
    "MEHERPUR",
    "NARAIL",
    "SATKHIRA",
    "BOGRA",
    "CHAPAINABABGANJ",
    "JOYPURHAT",
    "PABNA",
    "NAOGAON",
    "NATORE",
    "RAJSHAHI",
    "SIRAJGANJ",
    "DINAJPUR",
    "GAIBANDHA",
    "KURIGRAM",
    "LALMONIRHAT",
    "NILPHAMARI",
    "PANCHAGARH",
    "RANGPUR",
    "THAKURGAON",
    "HABIGANJ",
    "MAULVIBAZAR",
    "SUNAMGANJ",
    "SYLHET"];


function addDistrict(){
    var sel = document.getElementById('txtEthnicity');
    for(var i = 0 ; i < districts.length; i++){
        var opt = document.createElement('option');
        opt.innerHTML = districts[i];
        opt.value = districts[i];
        sel.appendChild(opt);
    }
}